# Site settings
author: Connie Sanchez
title: Following my dreams
header-img: img/home-bg.png
email: msnchz04@gmail.com
copyright_name: Connie Sanchez
description: > # this means to ignore newlines until "baseurl:"
  What it took to overcome my hurdles
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: CSProd19
github_username:  CSProd19

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
